# Generated by Django 4.2.3 on 2023-07-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
