# Generated by Django 4.2.3 on 2023-07-18 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0006_remove_answer_author_answer_modify_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
